import Head from "next/head";
import dbConnect from "../lib/dbConnect";
import User from "../models/User";
import Feed from "@/components/Feed";
import Users from "@/components/Users";
import Widgets from "@/components/Widgets";
import Sidebar from "@/components/Sidebar";
import { useSession, signIn, signOut } from "next-auth/react";
import { useRouter } from "next/router";

export default function Admin({ users }) {
  const { status, data: session } = useSession({
    required: true,
    onUnauthenticated() {
      signIn();
    },
  });
  const router = useRouter();
  if (status === "loading") {
    return <></>;
  } else if (!session.user.admin) {
    router.push("/");
  } else
    return (
      <>
        <Head>
          <title>Twidemia</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* <link rel="icon" href="/favicon.ico" /> */}
          <link rel="icon" href="/Twidemia-logo.png" />
        </Head>

        <main className="flex min-h-screen max-w-7xl mx-auto">
          <Sidebar user={session.user} />
          {/* Feed */}
          <Feed
            content={{ header: "Admin", content: <Users users={users} /> }}
          />

          <Widgets />

          {/* Model */}
        </main>
      </>
    );
}

export async function getStaticProps() {
  try {
    // Try to connect the DB.
    await dbConnect();
    const users = await User.find({});
    return {
      props: { users: users },

      props: { users: JSON.parse(JSON.stringify(users)) },
    };
  } catch (e) {
    // If it cannot connect to DB, output log to console by using error flag.
    console.error(e);
  }
}
